completion:
	appspec completion share/appspec-spec.yaml --zsh  > share/completion/zsh/_appspec
	appspec completion share/appspec-spec.yaml --bash  > share/completion/bash/appspec.bash

pod:
	appspec pod share/appspec-spec.yaml > lib/appspec.pod

